### ISSUE TITLE
VS Code Version Incompatibility

### ISSUE THREAD

**Issue by mpdrsn** [samuelcolvin/jinjahtml-vscode#1]
While I acknowledge I'm not using the most recent version of Code, this extension will not work  with 1.20.0 due to version incompatibility.
![image](https://user-images.githubusercontent.com/29259176/41394234-7c1b2cf4-6f66-11e8-9c00-797621f79553.png)

Please at least add a minimum version requirement to the documentation.

**Comment by samuelcolvin** [comment]
Thanks for reporting. It might just be that I set the minimum version to 1.22 in package.json. 

If you lower that it might work fine?
