### ISSUE TITLE
Integrate Jinja HTML with VS Code's custom language server

### ISSUE THREAD

**Issue by nathan-barrett** [samuelcolvin/jinjahtml-vscode#109]
A recent PR was just merged in vscode (not sure exactly when it'll hit production) https://github.com/microsoft/vscode/pull/146731 that allows you to `contribute to html language server with a custom language` - and I was wondering if this would allow this extension to retain all of the excellent features (thanks @samuelcolvin!) while being able to leverage the features of the HTML language server from vscode.

Happy to take this on - but this would be something I get done in my spare time - so If anyone else has interest feel free to pick this up!

**Comment by samuelcolvin** [comment]
Thanks so much, I don't have time to lead this (flat out trying to get
pydantic-core and pydantic V2 released), but I'm happy to review PRs and
help where possible.
