### ISSUE TITLE
Jinja comments are the same color as target language comments.

### ISSUE THREAD

**Issue by eadlam** [samuelcolvin/jinjahtml-vscode#119]
They should be different colors, because they are different things.

**Comment by samuelcolvin** [comment]
They have different identifiers in the language definition, just your theme doesn't support different colours for the different tags.

If you develop your own theme, let me know here, I'd be happy to link to if from this repo.

**Comment by eadlam** [comment]
Ah, thank you. I was able to use this to set a custom color in settings.json.

```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment.block.jinja"
                ],
                "settings": {
                    "foreground": "#d3d7cf",
                }
            }
        ]
    }
```

**Comment by samuelcolvin** [comment]
Great, hopefully this can help others.

Thanks.
