### ISSUE TITLE
Jinja comments not correctly highlighted in script tags

### ISSUE THREAD

**Issue by zmwangx** [samuelcolvin/jinjahtml-vscode#12]
I'm using some Jinja comments in an inline script tag (so that users do not see the comments — the template is directly rendered), but the comments aren't properly highlighted. A simple demo:

```jinja
{# blah #}
<script>
{# blah #}
// blah
/* blah */
</script>
```

<img width="84" alt="screen shot 2019-01-16 at 11 36 36 am" src="https://user-images.githubusercontent.com/4149852/51263977-5d67ba80-1983-11e9-98f3-ab8a07ad1f2a.png">

I wonder if it's easy to add proper support for Jinja comments within script tags.

**Comment by samuelcolvin** [comment]
Not that easily, I didn't write the `tmLanguage` files myself but rather took them from https://github.com/mitsuhiko/jinja2-tmbundle and converted them to JSON.

Perhaps you could try tweaking https://github.com/samuelcolvin/jinjahtml-vscode/blob/master/syntaxes/jinja.tmLanguage.json?

Is the problem specific to inside script tags or in general?

**Comment by zmwangx** [comment]
Thanks for the quick response. It's specific to script tags (at least I haven't found another context where comments are not recognized; but I've only used `jinja-html` mode, not raw, rb, md, or yaml). I'll take a look later.

**Comment by samuelcolvin** [comment]
`jinja-html` kind of "inherits" from raw, and applies it "on top" of html, except in this case it looks like it's not entirely on top.

I guess js is on top of html and jinja should be on top of both, but isn't in this case.

**Comment by lukesneeringer** [comment]
This is shockingly hard to do. I spent a lot of time playing with a variant of this problem elsewhere. The problem is that once something goes into one of the individual includes (e.g. `source.javascript`), any other include's matches are no longer checked.

This seems like the right thing to do in a lot of cases (e.g. a `<script>` tag in HTML dropping into JavaScript syntax highlighting) but it is the wrong thing for Jinja and similar templating languages, and there does not seem to be any way to tweak it.

**Comment by samuelcolvin** [comment]
I think relates to https://github.com/microsoft/vscode/issues/49210, realise I never linked to this issue.

**Comment by samuelcolvin** [comment]
Superseded by #55 which i think has the same root cause but describes the problem in a more succinct way.

**Comment by itskando** [comment]
Is this the same issue for jinja html not highlighting jinja comments in tags?

For example:

`<button {# disabled #} >`

blue: button disabled
yellow: {# #} 

where I would expect:

blue: button
green: {# disabled #}

**Comment by itskando** [comment]
Possible band-aid:

If correct `{# comment #}` coloring is important, the [django highlighter](https://github.com/vscode-django/vscode-django/) might be similar enough to jinja to use, and comments correctly color, (at least for my use case of the django html highlighter with .html).

Seen below is the django html highlighter:

![Image](https://github.com/user-attachments/assets/990e5715-955f-44a9-819a-d5248997815e)
