### ISSUE TITLE
Support `.yml.jinja`/`.yaml.jinja`

### ISSUE THREAD

**Issue by candrews** [samuelcolvin/jinjahtml-vscode#125]
According to jina, `.jinja` is the suggested template file extension:
https://jinja.palletsprojects.com/en/2.11.x/templates/#template-file-extension 

I see that this vs code plugin supports some yaml file extensions:
> Default file associations: .yml.j2, .yaml.j2 and .sls.

--- https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml

But not one that ends in `.jinja`

Can you please support the file extensions `yml.jinja` and `.yaml.jinja`?

**Comment by samuelcolvin** [comment]
PR welcome to add these.
