### ISSUE TITLE
custom start and end string?

### ISSUE THREAD

**Issue by swuecho** [samuelcolvin/jinjahtml-vscode#13]
if I change the jinja2 option: 

        block_start_string='<%',
        block_end_string='%>',
        variable_start_string='${',
        variable_end_string='}',
        comment_start_string='<#',
        comment_end_string='#>',

it would be great this can be configed in better jinja as well.

**Comment by samuelcolvin** [comment]
I think this is not simple as it would require a whole new [`jinja.tmLanguage.json`](https://github.com/samuelcolvin/jinjahtml-vscode/blob/master/syntaxes/jinja.tmLanguage.json).

Unless there's some other clever way I don't know of?

**Comment by pawamoy** [comment]
I'd like this this feature as well. I don't really know how VS Code extensions work, but I believe you can have extension settings that the user can change on a project, host or global basis.
