### ISSUE TITLE
Detecting control flow structures

### ISSUE THREAD

**Issue by adsharma** [samuelcolvin/jinjahtml-vscode#28]
With the following example:

`{% if foo() %}
    def bar():
        for i i range(10):
            print("hello")
{%elif xxx() %}
{{hello}}
{% for x in getrange() %}
    {{x}}
{% endfor %}
{%else}
{{bye}}
 def baz():
        for i i range(10):
            print("hello")
{% endif %}`

I'd like to be able to expand and collapse the if/elif/else/endif structure as well as the for loop template. I can't get it to work in either jinja or jinja-python mode.

**Comment by adsharma** [comment]
Fixed formatting: 

```
{% if foo() %}
    def bar():
        for i i range(10):
            print("hello")
{%elif xxx() %}
{{hello}}
{% for x in getrange() %}
    {{x}}
{% endfor %}
{%else}
{{bye}}
 def baz():
        for i i range(10):
            print("hello")
{% endif %}
```

**Comment by samuelcolvin** [comment]
I've no idea if this is possble through `tmLanguage.json`, my suspicion is not, but let me know if it can.

By the way, v0.10.3 #29 should fix jinja-python support.

**Comment by lukesneeringer** [comment]
I believe the author is asking for code folding, which is definitely possible.

Explicitly: I believe the author is _not_ asking for auto-formatting (indenting, etc.), and the follow-up post was merely to correct a formatting error on the original post. Auto-formatting would be neither possible nor desirable.

**Comment by samuelcolvin** [comment]
is it still a problem after the new release?

**Comment by lukesneeringer** [comment]
It is just a fundamentally orthogonal request.

**Comment by samuelcolvin** [comment]
I just wondered if vscode was clever enough to work it our from a valid `tmLanguage.json` files along, turns out it's not.
