### ISSUE TITLE
add formatting option

### ISSUE THREAD

**Issue by hellt** [samuelcolvin/jinjahtml-vscode#3]
Thanks for this awesome plugin.

Is it possible to add formatting option that will expand `flat` like templates with `for/if` statements into the indented ones? Example:

Input:
```
{% if a %}
var_a: someval
{% endif %}
{% if b %}
{% if c %}
c: someval
{% else %}
c3: someval
{% endif %}
b: someval
{% endif %}
```

Output:

```
{% if a %}
  var_a: someval
{% endif %}
{% if b %}
  {% if c %}
    c: someval
    c2: someval
  {% else %}
    c3: someval
  {% endif %}
b: someval
{% endif %}
```

**Comment by samuelcolvin** [comment]
see https://github.com/Microsoft/vscode/issues/49210, the short answer is "no" I'm afraid. There's no way to proxy advanced html formatting features on to the `html-jinja` language and implementing this from scratch is beyond the bounds of this project.
