### ISSUE TITLE
Support systemd unit files 

### ISSUE THREAD

**Issue by guhcampos** [samuelcolvin/jinjahtml-vscode#30]
I guess a lot of Ansible people might be already using this great extension, like me.

For this use case, it would be really cool to have `.service.j2` correctly displayed in vscode, as this is a very common pattern for templating systemd unit files.

Thanks for the great work!

**Comment by samuelcolvin** [comment]
happy to accept a PR, should just be a couple of lines.

**Comment by joshreep** [comment]
@samuelcolvin I just created a PR for this.  Let me know your thoughts.
