### ISSUE TITLE
Support json.j2 files

### ISSUE THREAD

**Issue by n-a-sz** [samuelcolvin/jinjahtml-vscode#31]
It would be great to have a json integration as well.
Thanks for the extension, works well!

**Comment by samuelcolvin** [comment]
> Thanks for the extension, works well!

No problem, thanks for using it.

PR welcome to add a `json` integration - it's pretty simple just a few files to add. Take a look at #26 for example.

**Comment by n-a-sz** [comment]
Thanks for the example, I have added a pull request based on that.
Did not test it.

**Comment by samuelcolvin** [comment]
fixed by #33

**Comment by n-a-sz** [comment]
Thanks for putting this into release.
Unfortunately, it is have some bugs: cannot find j2 expressions between double apostrophes and all other j2 expressions displayed with red color. But at least macros at the top of the file renders well and json syntax highlight works as well, so it is definitely easier to see what I'm doing.
For now, I cannot really debug this, maybe I'll have a look into it in the future.

**Comment by samuelcolvin** [comment]
I would guess the same as #12, afraid I have no idea of a solution for that.
