### ISSUE TITLE
Question no Intellisense and Snippets for jinja-yaml languge

### ISSUE THREAD

**Issue by hatifnatt** [samuelcolvin/jinjahtml-vscode#32]
Can't find solution by myself. How to get Intellisense and Snippets working with `jinja-yaml` language?
Everything is fine with `jinja-raw` or with `jinja-html`, `jinja-python` etc. auto suggestions and snippets are working, but with `jinja-yaml` they are not working. Although I can get suggestions using `Ctrl+Space` hotkey they don't work 'on-type'.
I can assume that because without extension (like redhat.vscode-yaml) automatic suggestions does not working for `yaml` language. 
But may be it's possible to make it work when above-mentioned extension is installed?
Please see attached images for details.
User snippet is suggested.
![jinja-raw](https://user-images.githubusercontent.com/807283/59041056-16cb1c00-88a2-11e9-8c25-29659d37764f.png)
Intellisense automatically show suggestions. `redhat.vscode-yaml` installed.
![yaml](https://user-images.githubusercontent.com/807283/59041058-1763b280-88a2-11e9-843e-e80456be013f.png)
Nothing happens.
![jinja-yaml](https://user-images.githubusercontent.com/807283/59041057-1763b280-88a2-11e9-8b69-38b89c8a51d8.png)

**Comment by samuelcolvin** [comment]
are you sure it works for `jinja-raw` and `jinja-python` etc.?

I think snippets are only working for `jinja-html` because of [this](https://github.com/samuelcolvin/jinjahtml-vscode/blob/master/package.json#L200). 

In your first screenshot above it says "(User Snippet)" which makes me think you've setup those snippets yourself somehow.

I guess either:
* setup more user snippets for `jinja-yaml`
* or add snippets to `jinja-yaml` here as a pull request following the format from #11, I'll review and merge then everyone can benefit from it.

**Comment by hatifnatt** [comment]
You right, I add [user snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) (actually just one for testing) and they are popup automatically for many `jinja-*` languages except `jinja-yaml`. 

Currently I don't have any snippets except few ones which I use for testing. When I get them working, and gather a collection, than I will create  pull request :)
I made it work with this configuration in `settings.json` 
```json
"[jinja-yaml]": {
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "editor.snippetSuggestions": "inline"
}
```
but may be there is another solution.
And more important, I still don't understand why for some languages Intellisense work "out of the box" and for another one it require manual actions.

**Comment by samuelcolvin** [comment]
No idea I'm afraid, I looked earlier but couldn't see anything different about how jinja-yaml is implemented. Let me know if you find anything.

By the way, most of the snippets used in jinja-html are not specific to html I think, you might just be able to copy them.

**Comment by hatifnatt** [comment]
I still think it's caused by "parent" languages, in this case by YAML, but I still don't know how to fix it i.e. with a help of `redhat.vscode-yaml` extension. This issue can be closed as I found workaround (can't call it a 'solution') mentioned above. If I will find something better I'll add it later.
Btw thanks for extension, it solved my `.sls` syntax highlight problem.
