### ISSUE TITLE
Add support for TOML files

### ISSUE THREAD

**Issue by Hipska** [samuelcolvin/jinjahtml-vscode#34]
Would be nice if support for `.toml.j2` could be added as well.

**Comment by samuelcolvin** [comment]
Happy to accept a PR to add this.

**Comment by Hipska** [comment]
Is it as easy as creating a `jinja-toml.tmLanguage.json` file with correct settings?

**Comment by samuelcolvin** [comment]
more or less, few other files to edit. See #33 which covers everything that's required.
