### ISSUE TITLE
Support VSCode Outline

### ISSUE THREAD

**Issue by ingshtrom** [samuelcolvin/jinjahtml-vscode#36]
VSCode has an outline mode but nothing shows up when using the Jinja YAML syntax. When I switch to my YAML syntax (builtin syntax, I believe?), it shows up correctly. For large files I find the outline mode very useful, but have to continually switch between different syntaxes to achieve this :(

Thanks for this work so far, it's been awesome to use!

**Comment by samuelcolvin** [comment]
thanks for the question, I suspect it's not possible to fix.

vscode has lots of power features that get disabled when creating your own syntaxes. 

Eg. in HTML mode vscode has lots of intelligent HTML features which get disabled when you use a language that's derived from  HTML, but isn't actually HTML. I dug into this a lot and the short answer is "it's not possible".

However if you find I'm wrong in that suggestion or things have changed, I'd be happy to try and improves things.

**Comment by ingshtrom** [comment]
Gotchya. I think if we actually used the API and provided symbols for the languages instead of only providing syntax highlighting, I _think_ it would work. I'm going to test out this idea and will report back if I have any findings.

For posterity, I also tried the [CodeMap extension](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.codemap) and it also didn't work.
