### ISSUE TITLE
Feature request: Add support for Dockerfile jinja2 templates

### ISSUE THREAD

**Issue by jsynowiec** [samuelcolvin/jinjahtml-vscode#4]
Add syntax highlighting for Dockerfile jinja(2) templates. There is no such extension right now and we have to switch back and forth between Dockerfile and jinja-raw syntax.

I was able to get some basic support _including_ patterns from docker and jinja but it couples this extension with the vscode-docker one. Not sure if this is a good idea.

**Comment by samuelcolvin** [comment]
Done. Would be great if you could take a second to [review Better Jinja](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml).
