### ISSUE TITLE
[Feature Request] Allow {{ansible_managed}}

### ISSUE THREAD

**Issue by lonix1** [samuelcolvin/jinjahtml-vscode#40]
In a `docker-compose.yml.j2` file, this may exist:

````
{{ansible_managed}}
````
or
````
{{ansible_managed | comment}}
````
etc.

It is typically found at the top (though may appear anywhere). It breaks syntax highlighting.

This should be allowed.

**Comment by samuelcolvin** [comment]
this should work fine. Please could you explain what's not working?

**Comment by lonix1** [comment]
thanks
