### ISSUE TITLE
Weird formatting issue

### ISSUE THREAD

**Issue by zilton7** [samuelcolvin/jinjahtml-vscode#41]
Hey,
So I get weird line breaks like this:
<img width="671" alt="Screen Shot 2019-11-22 at 17 38 15" src="https://user-images.githubusercontent.com/38778743/69439287-5356db00-0d4f-11ea-83ff-1c318f310292.png">

How it supposed to look:
<img width="897" alt="Screen Shot 2019-11-22 at 17 37 48" src="https://user-images.githubusercontent.com/38778743/69439333-649fe780-0d4f-11ea-9fe7-8f6c5f6e903d.png">

any way to fix this? :)

**Comment by samuelcolvin** [comment]
Not really possible I'm afraid, I guess it's a problem with vscode itself that the formatter doesn't respect the jinja parts of the file and uses (I guess) the standard formatting rules for javascript.

**Comment by zilton7** [comment]
actually, it seems I have fixed it by wrapping if statement in  parenthesis ;)
<img width="410" alt="image" src="https://user-images.githubusercontent.com/38778743/69440020-b4cb7980-0d50-11ea-87ea-d8d09c41288f.png">
