### ISSUE TITLE
Jinja Raw comment syntax wrong

### ISSUE THREAD

**Issue by jzielke84** [samuelcolvin/jinjahtml-vscode#45]
When using jinja raw in VSC and hitting the comment-out shortcut, the line get's prefixed with `#` rather than being embedded in `{# ... #}` which is not a jinja2 comment but rather a generic linux-style comment while it's still being interpreted by ansible as part of the template.

**Comment by samuelcolvin** [comment]
Thanks for reporting. Shouldn't be too hard to fix. Would you like to submit a PR?

**Comment by jzielke84** [comment]
@samuelcolvin I'm not really familiar with writing plugins for VSC. But after cloning the repo and looking at syntaxes/jinja.tmLanguage.json I see the following block:

```json
   {
      "begin": "{#-?",
      "captures": [
        {
          "name": "entity.other.jinja.delimiter.comment"
        }
      ],
      "end": "-?#}",
      "name": "comment.block.jinja"
    },
```

So maybe it's not a bug but more a misconfiguration of VSC itself. If anyone has a clue on how to fix that, I'd be happy to know.

**Comment by patel33hardik** [comment]
Can I use, javascript comment /* */ in my jinja HTML  ??

**Comment by samuelcolvin** [comment]
yes you can use them, but I don't think it's easy to get the comment shortcut to use other comment formats.

if you find otherwise, happy to accept a PR.

**Comment by StoneLabs** [comment]
I think this is fixed. Or perhaps it's an issue unrelated to this extension.

Hitting `Ctrl`+`K`,  `Ctrl`+`C` or `Shift`+`Alt`+`A` in a jinja file works just fine and comments out with `{# ... #}` as expected.
