### ISSUE TITLE
shell scripting support: .sh.j2

### ISSUE THREAD

**Issue by ssbarnea** [samuelcolvin/jinjahtml-vscode#5]
Ansible users do often use jinja2 templating on shell (bash) scripts so having the ability to recognize templates shell scripts would be extreamly useful.

**Comment by samuelcolvin** [comment]
fine by me, happy to accept a PR.

**Comment by ssbarnea** [comment]
Not sure if this should be closed. Is valid, desired, should stay open and with a need-help label attached to it.

**Comment by samuelcolvin** [comment]
Done, fixed in #16 and deployed. Would be great if you could take a second to [review Better Jinja](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml).
