### ISSUE TITLE
could you please add a jinja-nginx syntax?

### ISSUE THREAD

**Issue by tagirb** [samuelcolvin/jinjahtml-vscode#57]
as described in the subject, would be great to support a combination of nginx and jinja syntaxes.

**Comment by samuelcolvin** [comment]
PR welcome to add it - relatively easy since you should be able to copy another PR.

**Comment by tagirb** [comment]
Fair enough :) There you go: https://github.com/samuelcolvin/jinjahtml-vscode/pull/58, sorry, not tested yet.
