### ISSUE TITLE
Folding not consistently working

### ISSUE THREAD

**Issue by dwt** [samuelcolvin/jinjahtml-vscode#6]
Hi there,

I'm not yet sure what exactly the problem is, but it seems that the jinja highlighter is messing up the folding support somehow.

What I'm seeing:
* Cannot fold html elements (consistently)
* Cannot fold `{% block foo %}` elements consistently

Not sure if the reasons for that are the same. My current theory is that this happens if a (otherwise foldable) block contains content that is outdented. I.e.

```jinja
{% block foo %}
    fnord foo
{% endblock %}
```

this is foldable, but this is not

```jinja
{% block foo %}
fnord foo
{% endblock %}
```

which is super annoying.

**Comment by samuelcolvin** [comment]
This is a limitation of vscode. Basically when you use an alternative language like `jinja` you lose lots of the more powerful features of the html language.

Nothing I can do about it.
