### ISSUE TITLE
HTML file icon not appearing

### ISSUE THREAD

**Issue by tinmarr** [samuelcolvin/jinjahtml-vscode#61]
Could you add the HTML file icon in the File Explorer?

**Comment by samuelcolvin** [comment]
Maybe, if you can find out how, happy to accept a PR.

**Comment by thekashifmalik** [comment]
@tinmarr see my answer at https://github.com/samuelcolvin/jinjahtml-vscode/issues/74#issuecomment-709838846

**Comment by samuelcolvin** [comment]
Let's discuss on #74.
