### ISSUE TITLE
HTML snippets and Emmet not running

### ISSUE THREAD

**Issue by ankitjt** [samuelcolvin/jinjahtml-vscode#62]
After adding 'jinja-html' in files.associations jinja highlighting is working but somehow snippets like p + tab or any emmet snippets have stopped working.

I have even restarted VSC and disabled enabled the extension but still no other snippets in .html files are working.

Is that an issue with the extension??

**Comment by samuelcolvin** [comment]
see #55 and associated issues. This is a limitation of vscode.

**Comment by ankitjt** [comment]
adding "emmet.includeLanguages":{ "jinja-html": "html"}, worked.
Thanks for the reference.

**Comment by samuelcolvin** [comment]
That's useful, thank you.
