### ISSUE TITLE
Syntax highlighting when using Jinja tags inside HTML tags

### ISSUE THREAD

**Issue by n-wagner** [samuelcolvin/jinjahtml-vscode#65]
Syntax doesn't seem to highlight if you're doing something like the below.

```html
<div
  id={{ myId }}
  {% if myCondition %}
    class="myclass1"
  {% else %}
    class="myclass2"
  {% endif %}
></div>
```

Equivalently the control flow operators can be moved outside the tags and the highlighting will work, but this requires duplicating the tag.

```html
{% if myCondition %}
  <div class="myclass1">
{% else %}
  <div class="myclass2">
{% endif %}
</div>
```

Setting an attribute doesn't have an equivalent as far as I am aware. Probably should allow it to be enclosed in strings too like the below as per [this](https://stackoverflow.com/a/26004854/12301329).

```html
<div
  id="{{ myId }}"
></div>
```

**Comment by samuelcolvin** [comment]
this is a limitation of the syntax highlighter.

Simply use `<div id="{{ myId }}"`

**Comment by n-wagner** [comment]
Just to be clear, the quoting won't solve the issue of the syntax highlighting as of present. Was also wondering if this is a limitation of this given plugin, or a deeper one like some VS Code issue? Thanks!

**Comment by samuelcolvin** [comment]
Same route cause as #59 I think. An issue with vscode.
