### ISSUE TITLE
Can you add support for # syntax as well? 

### ISSUE THREAD

**Issue by lipis** [samuelcolvin/jinjahtml-vscode#7]
example: https://github.com/gae-init/gae-init/blob/master/main/templates/user/user_list.html

**Comment by lipis** [comment]
I would submit if I had time..

**Comment by samuelcolvin** [comment]
afraid this is a big change to highlighting. If there's an existing tmLanguage file which covers this case I can integrate it, otherwise it won't be possible.

**Comment by lipis** [comment]
Thanks man..
