### ISSUE TITLE
.json.jinja extension highlighting code wrong

### ISSUE THREAD

**Issue by Yajo** [samuelcolvin/jinjahtml-vscode#73]
See how it looks like:

![imagen](https://user-images.githubusercontent.com/973709/92882703-148e3080-f408-11ea-9802-005f6e22061c.png)

As you can see, the JSON Jinja syntax is properly selected by vscode, but the actual code is not highlighted as expected.

**Comment by samuelcolvin** [comment]
I don't really know what to suggest. [`jinja-json.tmLanguage.json`](https://github.com/samuelcolvin/jinjahtml-vscode/blob/master/syntaxes/jinja-json.tmLanguage.json) is very simple it just says "combine JSON and jinja languages with jinja taking priority".

If vscode interprets that wrong, I doubt there's much we can do. Unless there's someway to change `jinja.tmLanguage.json` to somehow give it priority?
