### ISSUE TITLE
[Feature request] Highlight jinja code inside quotation marks

### ISSUE THREAD

**Issue by andreclaro** [samuelcolvin/jinjahtml-vscode#8]
Hello,

First of all, thank you for your fantastic job creating this plugin.

I would like to give feedback regarding YAML Jinja file. It would be very useful if the plugin can highlight the jinja2 code inside quotation marks. For example {{ table }} and {{ operation }} in the below example.

Example Cloudformation file (yaml) with jinja2:

```
...
{% for operation in ('Read', 'Write') %}
  {{ table | replace("-", "")}}Throttle{{ operation }}WarnAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: {'Fn::Sub': '${Stage}-{{ table }}-Throttle{{ operation }}Warn'}
 ...
```

Best regards,
André

**Comment by samuelcolvin** [comment]
(updated your issue to make it readable)

As far as I know this is a limitation of the underlying language highlighting definitions and therefore not fixable by me.
