### ISSUE TITLE
Syntax not highlighted properly for JSON numeric values 

### ISSUE THREAD

**Issue by TheZbunj** [samuelcolvin/jinjahtml-vscode#88]
If there is *json.j2 file that has numeric values (that are not surrounded by double quotes) syntax is not highlighted properly.

This one is ok:
```
{
  "a": "{{ a }}",
  "b": "{{ b }}",
  "c": "{{ c }}"
}
```

![image](https://user-images.githubusercontent.com/63349917/114859698-63aba200-9deb-11eb-93b2-3989f10ec7b4.png)

This one is not ok:
```
{
  "a": "{{ a }}",
  "b": {{ b }},
  "c": "{{ c }}"
}
```
![image](https://user-images.githubusercontent.com/63349917/114859985-bc7b3a80-9deb-11eb-8c66-53ff5f0197ed.png)

**Comment by samuelcolvin** [comment]
probably the same as #12 - long standing issue but I don't know of a fix.
