### ISSUE TITLE
adding alternate extension not honored until reload

### ISSUE THREAD

**Issue by dkebler** [samuelcolvin/jinjahtml-vscode#89]
I use jinja2 in yaml within home assitant context.  If I use the .j2 extension then home assistant does not recognize that file for rendering nor for the home assistant extension.  

Thus I decided to use `.j2.yaml`  instead of `.yaml.j2`.  So I add that to my settings.json.  The file is autodected as jinja yaml fine but if I have just come from `home assistant`  language the file show errors until I reload vscode.  Thus every time I flip from `home assistant` language to `jinja-yaml` I must reload vscode.   Not sure if this is a vscode thing or the extension is not internally reloading/updating when the language is changed.    

```json
    "files.associations": {
        "env": "shellscript",
        "*.mod": "shellscript",
        "*.nemo_action": "shellscript",
        "*.yaml": "yaml",
        "*.j2.yaml": "jinja-yaml"
    },
```

**Comment by samuelcolvin** [comment]
that's weird, I haven't seen this before.

But I don't think it's a problem with this plugin, or something that can be fixed in this plugin.
