### ISSUE TITLE
Multiline string syntax highlighting?

### ISSUE THREAD

**Issue by philippefutureboy** [samuelcolvin/jinjahtml-vscode#91]
Hey there!

I was wondering if there is any support / plan for support for syntax highlighting of strings in other programming languages, like [Highlight String Code](https://marketplace.visualstudio.com/items?itemName=iuyoy.highlight-string-code) does it for HTML/CSS/SQL?

I think that would be a rather awesome functionality :D

What do you think?

Cheers!
Philippe

**Comment by samuelcolvin** [comment]
probably the same as #12 - long standing issue but I don't know of a fix.
