### ISSUE TITLE
Multiline comments inside cpp-namespace

### ISSUE THREAD

**Issue by bigoulours** [samuelcolvin/jinjahtml-vscode#93]
Multiline comments are not correctly highlighted after I declare a namespace in cpp:
![jinja_com_screenshot](https://user-images.githubusercontent.com/29359842/125779734-03724ede-0f7a-4a4c-bdb0-c9dfefbf3db8.PNG)

**Comment by samuelcolvin** [comment]
probably the same as #12 - long standing issue but I don't know of a fix.
