### ISSUE TITLE
Mardown syntax not working when var or block does not begin in the first char of a line

### ISSUE THREAD

**Issue by jtplaarj** [samuelcolvin/jinjahtml-vscode#98]
Mardown syntax not working when var or block does not begin in the first char of a line.

For example:

```markdown
# whatever

{% for x in whatever %}
{{ x }}
{% endfor %}
```
works but

```markdown
# whatever

{% for x in whatever %}
- {{ x }}
{% endfor %}
```

does not

**Comment by RedCMD** [comment]
Caused by the Markdown grammar
![image](https://user-images.githubusercontent.com/33529441/185728167-d48fa5f2-e1e3-4aec-9bb5-25da11e56949.png)

It may be possible to setup `injections` to fix it, but would very likely end up causing more issues

**Comment by samuelcolvin** [comment]
Thanks for the explanation, closing.
